### ISSUE TITLE
Option to select video and audio devices

### ISSUE THREAD

**Issue by fmeringdal** [fmeringdal/nettu-meet#1]
Currently only the default device will be selectable, it would be nice to give the user a list of the possible devices to get the media stream from.

**Comment by nikhil-chaurasia14** [comment]
Hi @fmeringdal, 
I would like to solve this issue but facing build error regarding mongodb authentication. 
Please can you help me out?
![image](https://user-images.githubusercontent.com/54658341/121741195-d307ee80-cb1b-11eb-8fa1-0b9f64b1f7e0.png)

**Comment by fmeringdal** [comment]
Hi @nikhil-chaurasia14 !
Great that you would like to tackle this :)

In your `.env` file try changing `MONGODB_NAME="test"` to `MONGODB_NAME="nettu-meeting"`.
