### ISSUE TITLE
Nettu meet questions

### ISSUE THREAD

**Issue by miroslavpejic85** [fmeringdal/nettu-meet#12]
Hi @fmeringdal  `Nice work!` 🙂

I have just a 2 questions:

1) `How many` participants are `supported in the room`?
2) `Does it compatible` with `all mobile devices`?
 
Keep it up! 💪

**Comment by fmeringdal** [comment]
Hi, thanks! :)

1. There isn't really a strict limit on the number of participants in a room. I guess that 20-30 people should work fine, but I have not tested that. How many do you anticipate to have in your rooms?
2. Mobile devices are not supported yet unfortunately :(

**Comment by miroslavpejic85** [comment]
Regarding the first question, try to enter in the `same room` with `7 participants` and tell me if you see `the seventh correctly`? For Mobile devices ok, it still remains a very good web-app! 😉 and I'll put you a nice ⭐️ too.

**Comment by fmeringdal** [comment]
Oh nice catch, seems like there is a bug in the layout logic when the number of participants is either 7 or 8. So they dont show up in the UI, but they are in the meeting. If you add 9 or more participants you will see them in the UI

**Comment by miroslavpejic85** [comment]
I like you use `mediasoup` as `SFU` backend `server`. In this way in theory you can have `large number` of `user` in the `single room`. I need to implement too! 😅
If we `merges` [Mirotalk](https://github.com/miroslavpejic85/mirotalk) and `Nettu Meet`!
I think it would `compete well` with other `similar paid web-apps`, except that we offer a nice `free` and `open source solution`! 😎

**Comment by miroslavpejic85** [comment]
And that they are two completely differently structured projects, I made it `easier` for `beginners`. I would miss the integration of the `mediasoup server` that you have alredy integrated in `nettu meet`. You would miss something like compatibility with mobile devices etc. that `mirotalk` has. For that I said hypothetically if the two projects were born together with all `your features and mine`, it would have been the top! 🌟

**Comment by fmeringdal** [comment]
For sure both of our projects have pros and cons and can supplement and learn from each other, no doubt about that 🙌
