### ISSUE TITLE
Meeting will start in long time

### ISSUE THREAD

**Issue by kevinadhiguna** [fmeringdal/nettu-meet#14]
Hello @fmeringdal, thank you for your nice work !

I would like to ask how should I start a meeting because I clicked the New Meeting button on the homepage and it says the meeting will start in 479 minutes :
![image](https://user-images.githubusercontent.com/43397636/121651946-5ba77000-cac5-11eb-99ee-d1c6ffc8add3.png)

Steps to reproduce : 
1. Go to <https://meet.nettubooking.com/>.
2. Click the `New Meeting` button.
3. Go to a newly opened tab.
4. See the screenshot above.

Tested with Firefox. Any response will be appreciated.

**Comment by fmeringdal** [comment]
Thanks for reporting this.
Seems like your browser time is wrong somehow. Do you get the correct time if you open your dev console and type: `new Date()` ?

**Comment by kevinadhiguna** [comment]
This time, it said the meeting has finished but there is an account id : 

![image](https://user-images.githubusercontent.com/43397636/121693383-46e1d100-caf3-11eb-9eae-fe5c5d3e2061.png)

**Comment by kevinadhiguna** [comment]
Tested with Google Chrome as well : 

![image](https://user-images.githubusercontent.com/43397636/121694241-249c8300-caf4-11eb-9105-baa7268c9633.png)

**Comment by fmeringdal** [comment]
Mhm, the relevant part is the `openingTime` attribute that you see in the object.
Do you mind clicking on create meeting and then say what these three values are:

1. `openingTime.startTS`
2. `openingTime.endTS`
3. `new Date().valueOf()`

The third value should be a value between 1 and 2

**Comment by kevinadhiguna** [comment]
Suddenly the errors disappeared : 

![image](https://user-images.githubusercontent.com/43397636/121701001-ab545e80-cafa-11eb-9340-3572b8d8ca4c.png)

and yes, the `new Date().valueOf()` value was a value between `openingTime.startTS` and `openingTime.endTS`. I do not why...

**Comment by fmeringdal** [comment]
Very strange. I do suspect that there is some instability with your browser / system time that is causing this.

**Comment by kevinadhiguna** [comment]
Thank you for your time @fmeringdal , I really appreciate it.
