### ISSUE TITLE
Installtion issue.

### ISSUE THREAD

**Issue by nabad600** [fmeringdal/nettu-meet#16]
I try to install my system, (Windows 10) it's npm error under server, also try ubuntu 20.04 but same issue.

![image](https://user-images.githubusercontent.com/67466982/122575140-0f80a080-d06e-11eb-8cf4-daca89f1555f.png)

**Comment by fmeringdal** [comment]
This seems like an issue with `npm` and not an error with this project.

Maybe try some of the suggestions listed [here](https://github.com/npm/npm/issues/10826) and see if that works.
