### ISSUE TITLE
Why do I listen to myself? 

### ISSUE THREAD

**Issue by jhonnyalphas** [fmeringdal/nettu-meet#20]
I should just listen to others.

**Comment by jhonnyalphas** [comment]
I am the only person in a room and I listen to what I speak through my microphone

**Comment by fmeringdal** [comment]
Nice catch! 
The local `audio` element was not muted.
I updated the code now, let me know if the problem persists.

**Comment by jhonnyalphas** [comment]
Ready, thanks.
