### ISSUE TITLE
Can not read property setWidth of undefined

### ISSUE THREAD

**Issue by Wyfy0107** [fmeringdal/nettu-meet#24]
I encountered this error on the first run of the project. Refresh a few times and it was gone so I did not have a chance for screenshot. The error stems from line 86, `CanvasManager.ts`

**Comment by Wyfy0107** [comment]
Got a screenshot, this happened when I try to resize the screen

<img width="1125" alt="Screenshot 2021-06-25 at 17 07 28" src="https://user-images.githubusercontent.com/63753802/123436943-d4372200-d5d7-11eb-9610-c79e17078f82.png">

**Comment by fmeringdal** [comment]
Thanks for reporting this issue. It should be fixed now
