### ISSUE TITLE
Color picker for sketch

### ISSUE THREAD

**Issue by LEEYOONJONG** [fmeringdal/nettu-meet#27]
Currently only a few default colors can be selected. It would be nice to give more options for color.
example) https://casesandberg.github.io/react-color/

**Comment by JustKode** [comment]
#28 
So, I added some code to implement the above functions.

**Comment by LEEYOONJONG** [comment]
What a GENIUS!

**Comment by fmeringdal** [comment]
Hi @JustKode , thanks for your PR!
I will review it later today

**Comment by fmeringdal** [comment]
Closed by #28
