### ISSUE TITLE
Edge browser support

### ISSUE THREAD

**Issue by fmeringdal** [fmeringdal/nettu-meet#9]

**Comment by mfkp** [comment]
https://github.com/fmeringdal/nettu-meet/blob/main/frontend/src/pages/EntryPage.tsx#L126

Maybe it does work on Windows (I see it's listed under a "Windows" category), but I am using Edge browser on Linux:

https://www.microsoftedgeinsider.com/en-us/download/?platform=linux

Version 92.0.884.2 (Official build) dev (64-bit)

**Comment by mfkp** [comment]
Also, I just noticed a typo here on this line:

https://github.com/fmeringdal/nettu-meet/blob/main/frontend/src/pages/EntryPage.tsx#L147

"bowser" should be "browser" :-)

![Bowser](https://vignette.wikia.nocookie.net/hello-yoshi/images/1/1a/New_Bowser_render.png/revision/latest/scale-to-width-down/310?cb=20190623212932)

**Comment by fmeringdal** [comment]
Thanks for the details! Edge + Linux is an interesting combo :grin: 
I think that edge should work regardless of OS as it uses chromium. So the only thing to do is to add an entry to the `supportedBrowsers` variable so that it matches with the linux + edge combo.

Do you want to try to fix that? Otherwise I will fix it when I have some time to spare :)

**Comment by mfkp** [comment]
Let me know when it's deployed/live and I'll test it out for you.

**Comment by fmeringdal** [comment]
Great! It should be live now

**Comment by mfkp** [comment]
Hm, I'm not seeing the updates yet (I made sure the cache is cleared and whatnot):

![screenshot](https://files.kylepowers.com/s/screenshot_2021-06-09_at_14:20:56.png)

**Comment by fmeringdal** [comment]
Oh looks like something is broken in the pipeline. I pushed the update manually now, and verified that that the updated version is live now.

**Comment by mfkp** [comment]
Perfect, just confirmed it's working great in Edge Browser on Linux :-)

**Comment by fmeringdal** [comment]
Awesome!  🎉  Thanks for helping out on this!
